### ISSUE TITLE
Q - how to set the mariadb datadir during installation

### ISSUE THREAD

**Issue by diepes** [rolehippie/mariadb#15]
Is it possible to set an alternative mariadb datadir during installation ?

What i have tried:

Currently i add it to "mariadb_extra_configs:"   datadir: /data/

I seem to run in chicken-egg problem where the mysql user does not exist before this role, but then when it runs it does not have access to the datadir.

Even after fixing the permission manually and running the playbook with this role again, the mariadb.service fails to start with error.
`[ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist`

Can fix this also manually with $ sudo cp -a /var/lib/mysql/* /data/

Summary:
How to use alternative datadir with this role ?

**Comment by tboerger** [comment]
This role doesn't provide an option to change the data path.

**Comment by diepes** [comment]
Thanks for the response.

Was able to achieve different data drive, by creating and symlinking /var/lib/mysql to new data dir and using this ansible role to deploy it.
Worked great, as this role fixes the user MySQL for the directory. (user does not exist when I create the symlink)
